### ISSUE TITLE
Error loading DqnAgent saved model.

### ISSUE THREAD

**Issue by andreclaudino** [tensorflow/agents#136]
I am creating a tf-agent DqnAgent in the following code:

```Python
    tf_agent = dqn_agent.DqnAgent(
        train_env.time_step_spec(),
        train_env.action_spec(),
        q_network=q_net,
        optimizer=optimizer,
        td_errors_loss_fn=dqn_agent.element_wise_squared_loss,
        train_step_counter=train_step_counter
)
```

During the training loop I am saving this model with

```Python
    tf.saved_model.save(tf_agent, saved_models_path)
```

Once trained, I want to load saved model with

```Python
    if tf.saved_model.contains_saved_model(saved_models_path):
        tf_agent = tf.saved_model.load(saved_models_path)
```

This code will load the saved model only if the folder in `saved_path` contains one, the functions `contains_saved_model(saved_models_path)` returns `True`, so the model is loaded, but there is an excetion and the program crashes:

```Python
    Traceback (most recent call last):
        File "/home/claudino/Projetos/dino-tf-agents/dino_ia/model/agent.py", line 50, in <module>
            tf_agent = tf.saved_model.load(saved_models_path)
        File "/home/claudino/Projetos/dino-tf-agents/venv/lib/python3.6/site-packages/tensorflow/python/saved_model/load.py", line 408, in load
            return load_internal(export_dir, tags)
        File "/home/claudino/Projetos/dino-tf-agents/venv/lib/python3.6/site-packages/tensorflow/python/saved_model/load.py", line 432, in load_internal
            export_dir)
        File "/home/claudino/Projetos/dino-tf-agents/venv/lib/python3.6/site-packages/tensorflow/python/saved_model/load.py", line 58, in __init__
            self._load_all()
        File "/home/claudino/Projetos/dino-tf-agents/venv/lib/python3.6/site-packages/tensorflow/python/saved_model/load.py", line 168, in _load_all
            slot_variable = optimizer_object.add_slot(
        AttributeError: '_UserObject' object has no attribute 'add_slot'

        Process finished with exit code 1
```

**Comment by allenlavoie** [comment]
Which TensorFlow version are you saving with? Export with slot variables wasn't working e.g. in the 2.0 alpha. I'd try a recent nightly.

**Comment by andreclaudino** [comment]
Thanks. I m using 2.0 beta, unfortunately, tf-nightly is not compatible with the code I could reach in tf-agents documentation.

This looks a bug, and on the other side, we need better documentation on tf-agents for stable tensorflow.

**Comment by allenlavoie** [comment]
The beta is fine, if you save with that you shouldn't see that exception. Which version did you save with?

**Comment by andreclaudino** [comment]
Are you saying it should work with tensorflow 2.0 beta?
I am saving and loading with the same version, the nightly one. I tried again updating both tensorflow and tf-agents, but the problem persists.

**Comment by allenlavoie** [comment]
Hrm. I'm guessing it's using a tf.compat.v1.train.* optimizer then? 2.x optimizers are pretty well tested.

**Comment by andreclaudino** [comment]
Yes, it's using `tf.compat.v1.train.AdamOptimizer(learning_rate=learning_rate)`.

Let me change and test again.

**Comment by andreclaudino** [comment]
Lets to the news:

I changed optimizer to `tf.optimizers.Adam(learning_rate=learning_rate)`

It gives me an error raising unknow parameter timestep, iton on `dqn-agent.py`

```
self._optimizer.apply_gradients(grads_and_vars,
                                    global_step=self.train_step_counter)
```

Just to give a try, I removed parameter global_step:

```
self._optimizer.apply_gradients(grads_and_vars)
```

I could train and save the model normally, but on loading, got a new error:

```
Traceback (most recent call last):
  File "/home/claudino/Aplicacoes/pycharm/helpers/pydev/pydevd.py", line 1758, in <module>
    main()
  File "/home/claudino/Aplicacoes/pycharm/helpers/pydev/pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/claudino/Aplicacoes/pycharm/helpers/pydev/pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/claudino/Aplicacoes/pycharm/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/claudino/Projetos/dino-tf-agent/dino_ia/model/agent.py", line 60, in <module>
    eval_policy = tf_agent.policy
AttributeError: '_UserObject' object has no attribute 'policy'
```

Finding solution without more examples and informations looks hard to me. Could you share a snippet ou a code where saving and loadin a model is successfull?

**Comment by andreclaudino** [comment]
If anyone could help, the code with problems is here:

https://github.com/andreclaudino/dino-tf-agent/tree/model-saving-test

In the branch `model-saving-test`.

**Comment by allenlavoie** [comment]
So if you use a 2.x Optimizer then it'll save and load, but the Agents code is expecting a "policy" function which isn't there? You may just have to add a `@tf.function` decorator on your policy function so that there's something to save there. (Disclaimer: I worked on TF SavedModel but not on Agents)

There are some unit tests using SavedModel which are run regularly: https://github.com/tensorflow/agents/blob/367d9c6ca5f6b8196036f193dcaa20597582b56b/tf_agents/policies/policy_saver_test.py#L250

**Comment by sguada** [comment]
@allenlavoie only 2.x Optimizers are suppose to work well? Currently we are still using 1.x Optimizers in TF-Agents.

**Comment by allenlavoie** [comment]
It's not hard to fix; basically there's a special case for 2.x optimizers which revives them as things you can store slot variables in. The optimizer doesn't need to be functional, it just needs to have a primary->slot variable mapping somewhere. But right, we don't have that special case for 1.x optimizers at the moment. Another workaround is to just delete the optimizer before saving if you don't need the slot variables.

**Comment by andreclaudino** [comment]
@sguada, do you have any example saving and restoring an agent?

**Comment by andreclaudino** [comment]
Sorry, I closed this issue, but it was a mistake.

> @allenlavoie only 2.x Optimizers are suppose to work well? Currently we are still using 1.x Optimizers in TF-Agents.

As I said, using 2.0 optiimizer drives me to an exception at `dqn_agent.py` (its a tf-agents package at `tf_agents.agents.dqn`), where the parameter global_step is not expected for optimizer. Error was raised using `tf.optimizers.Adam(learning_rate=learning_rate)`.

```
self._optimizer.apply_gradients(grads_and_vars,
                                    global_step=self.train_step_counter)
```

Looks removing this parameter make code perform well.

**Comment by andreclaudino** [comment]
> So if you use a 2.x Optimizer then it'll save and load, but the Agents code is expecting a "policy" function which isn't there? You may just have to add a `@tf.function` decorator on your policy function so that there's something to save there. (Disclaimer: I worked on TF SavedModel but not on Agents)
> 
> There are some unit tests using SavedModel which are run regularly:
> 
> https://github.com/tensorflow/agents/blob/367d9c6ca5f6b8196036f193dcaa20597582b56b/tf_agents/policies/policy_saver_test.py#L250

I can't apply `@tf.function` once this will not return a tensor.  The same happen with `collect_policy`, 
`batch_size` and `collect_data_spec`, but `collect_data_spec` cannot be replaced by it's hidden variable once it's a child at `_collect_policy.trajectory_spec`, and restored model don't found trajectory_spec too.

In tf-agents, the policy parameter is got by a property `tf-agent.policy`. Changing the property to the returned hidden variable `_policy`  do the trick.

**Comment by v-pourahmadi** [comment]
@andreclaudino I have the same exact issue, were you able to make the load/save working? do you have a working example that I can take a look?

**Comment by pana1990** [comment]
+1

**Comment by andreclaudino** [comment]
> @andreclaudino I have the same exact issue, were you able to make the load/save working? do you have a working example that I can take a look?

Unfortunatelly I have no solution to this problem yet.

**Comment by starkgate** [comment]
Same problem here, would love to see a fix or workaround

**Comment by Addyvan** [comment]
Any progress on this ? I would also love to see a workaround ! 

Is anybody currently saving and loading models successfully? I think being able to do so is pretty important for an RL package...

**Comment by starkgate** [comment]
Only loading/saving the weights works, but it's clearly far from ideal

**Comment by Addyvan** [comment]
> Only loading/saving the weights works, but it's clearly far from ideal

Are you doing this via the policy saver? I am currently able to export and make use of my trained policy but I haven't figured out how to resume training on my agent.

**Comment by starkgate** [comment]
Policy saver ? I'm using modelcheckpoints :

`cp_callback = tf.keras.callbacks.ModelCheckpoint(checkpoint_path, save_weights_only=True, verbose=1)`

**Comment by andreclaudino** [comment]
Thanks @CreeperLava, I will try.

**Comment by kbanoop** [comment]
We are planning to add a colab for policy saving, so I'm closing this issue in favor of #186.

I'll add a reference to this from #186.

**Comment by anuprulez** [comment]
Upgrading tensorflow to 2.7 from 2.6 solved the issue for me

```
/opt/conda/lib/python3.9/runpy.py:127: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
2021-11-25 20:33:30,584 - WARNING - '--tag' not specified for saved_model. Using --tag serve
2021-11-25 20:33:42,054 - INFO - Signatures found in model: [serving_default].
2021-11-25 20:33:42,055 - WARNING - '--signature_def' not specified, using first signature: serving_default
2021-11-25 20:33:42,057 - INFO - Output names: ['activation_2']
WARNING:tensorflow:From /opt/conda/lib/python3.9/site-packages/tf2onnx/tf_loader.py:706: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
2021-11-25 20:33:47,030 - WARNING - From /opt/conda/lib/python3.9/site-packages/tf2onnx/tf_loader.py:706: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
2021-11-25 20:33:52,639 - INFO - Using tensorflow=2.7.0, onnx=1.10.2, tf2onnx=1.9.3/1190aa
2021-11-25 20:33:52,640 - INFO - Using opset <onnx, 15>
2021-11-25 20:34:00,768 - INFO - Computed 0 values for constant folding
2021-11-25 20:34:05,944 - INFO - Optimizing ONNX model
2021-11-25 20:34:31,232 - INFO - After optimization: Add -1 (6->5), BatchNormalization -4 (20->16), Cast -8 (10->2), Concat -5 (14->9), Const -100 (272->172), Gather +1 (0->1), Identity -6 (6->0), Reshape +2 (4->6), Shape -5 (6->1), Slice -5 (6->1), Squeeze -6 (6->0), Transpose -91 (124->33), Unsqueeze -24 (24->0)
2021-11-25 20:34:31,990 - INFO - 
2021-11-25 20:34:31,990 - INFO - Successfully converted TensorFlow model gen_saved_model to ONNX
2021-11-25 20:34:31,990 - INFO - Model inputs: ['input_2', 'input_3']
2021-11-25 20:34:31,991 - INFO - Model outputs: ['activation_2']
2021-11-25 20:34:31,991 - INFO - ONNX model is saved at gen.onnx
```
