### ISSUE TITLE
Getting import error in TF-Agents Policies Tutorial.

### ISSUE THREAD

**Issue by drozzy** [tensorflow/agents#26]
When running a policies [tutorial](https://colab.research.google.com/github/tensorflow/agents/blob/master/tf_agents/colabs/3_policies_tutorial.ipynb#scrollTo=xsLTHlVdiZP3) collab, executing this cell:

```
import abc
import tensorflow as tf
import tensorflow_probability as tfp
import numpy as np

from tf_agents.specs import array_spec
from tf_agents.specs import tensor_spec
from tf_agents.environments import time_step as ts
from tf_agents.networks import network

from tf_agents.policies import py_policy
from tf_agents.policies import random_py_policy
from tf_agents.policies import scripted_py_policy

from tf_agents.policies import tf_policy
from tf_agents.policies import random_tf_policy
from tf_agents.policies import actor_policy
from tf_agents.policies import q_policy
from tf_agents.policies import greedy_policy

tf.compat.v1.enable_v2_behavior()
```

outputs this:

```
AttributeErrorTraceback (most recent call last)
<ipython-input-6-d447654fa582> in <module>()
      9 from tf_agents.networks import network
     10 
---> 11 from tf_agents.policies import py_policy
     12 from tf_agents.policies import random_py_policy
     13 from tf_agents.policies import scripted_py_policy

/usr/local/lib/python2.7/dist-packages/tf_agents/policies/py_policy.py in <module>()
     28 from tf_agents.environments import trajectory
     29 from tf_agents.policies import policy_step
---> 30 from tf_agents.utils import common
     31 
     32 

/usr/local/lib/python2.7/dist-packages/tf_agents/utils/common.py in <module>()
    289 
    290 
--> 291 class Periodically(tf.Module):
    292   """Periodically performs the ops defined in `body`."""
    293 

AttributeError: 'module' object has no attribute 'Module'
```

**Comment by sibyjackgrove** [comment]
Did you install the TF nightly build? I think TF-agents only work with TF nightly and TF 2.0

**Comment by oars** [comment]
Yep, looks like it's not on a nightly build. Thanks @sibyjackgrove!

**Comment by drozzy** [comment]
Yap, I am using explicitly with a nighly (tf 2.0). As can be seen in tutorial:

```
!pip install tf-nightly
!pip install tfp-nightly
!pip install tf-agents-nightly
```

**Comment by oars** [comment]
Are you running in a local runtime? I just clicked on the link you provided and am able to run the whole notebook on a hosted runtime without any exceptions.

**Comment by drozzy** [comment]
No, it was on colab.
Strange, now it works.

**Comment by oars** [comment]
Glad it works.
