### ISSUE TITLE
env.step(1) => AttributeError: 'int' object has no attribute 'item'

### ISSUE THREAD

**Issue by ageron** [tensorflow/agents#520]
The following code raises an exception:

```python
from tf_agents.environments import suite_gym

env = suite_gym.load('Breakout-v4')
env.reset()
env.step(1)
```

The exception is `AttributeError: 'int' object has no attribute 'item'`, and it occurs on line 212 of the file `environments/gym_wrapper.py` (see the full stacktrace below).

This used to work fine. I ran some tests, and apparently it broke in 0.4.0 (it works fine in 0.3.0).

Here is a simple workaround:

```
import numpy as np

env.step(np.array(1))
```

Here is the full stacktrace:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-16-550e74cbba45> in <module>
----> 1 env.step(1) # Fire

~/miniconda3/envs/tf2/lib/python3.7/site-packages/tf_agents/environments/py_environment.py in step(self, action)
    201       return self.reset()
    202
--> 203     self._current_time_step = self._step(action)
    204     return self._current_time_step
    205

~/miniconda3/envs/tf2/lib/python3.7/site-packages/tf_agents/environments/wrappers.py in _step(self, action)
    115       return self.reset()
    116
--> 117     time_step = self._env.step(action)
    118
    119     self._num_steps += 1

~/miniconda3/envs/tf2/lib/python3.7/site-packages/tf_agents/environments/py_environment.py in step(self, action)
    201       return self.reset()
    202
--> 203     self._current_time_step = self._step(action)
    204     return self._current_time_step
    205

~/miniconda3/envs/tf2/lib/python3.7/site-packages/tf_agents/environments/gym_wrapper.py in _step(self, action)
    210     # actions we have a numpy scalar (e.g array(2)) which is not hashable
    211     # in this case, we simply pull out the scalar value which will be hashable.
--> 212     action = action.item() if self._action_is_discrete else action
    213
    214     # TODO(oars): Figure out how tuple or dict actions will be generated by the

AttributeError: 'int' object has no attribute 'item'
```

**Comment by ageron** [comment]
See this Colab which reproduces the issue (and also shows that it used to work in 0.3.0):
https://colab.research.google.com/drive/18bWfUtpghrkb7oS-i1fSUECW2a2wIOon?usp=sharing
